export const metadata = {
  title: "Contact - My Next.js App",
  description: "Generated by create next app and my brain",
  keywords: "simple, nextjs, app, example",
};

const ContactPage = () => {
  return (
    <div>
      <h1>Contact Page</h1>
      <p>This is the contact page.</p>
    </div>
  );
};

export default ContactPage;
