import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create next app and my brain",
  keywords:"simple, nextjs, app, example"
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="navbar bg-primary shadow-sm text-primary-content">
          <div className="flex-1">
            <a className="btn btn-ghost text-xl">daisyUI</a>
          </div>
          <div className="flex-none">
            <ul className="menu menu-horizontal px-1">
              <li>
                <a>Link</a>
              </li>
              <li>
                <details>
                  <summary>Navigation</summary>
                  <ul className="bg-base-100 rounded-t-none p-2">
                    <li>
                      <Link className="btn btn-ghost normal-case text-xl" href="/">Home</Link>
                    </li>
                    <li>
                      <Link className="btn btn-ghost normal-case text-xl" href="/about">About</Link>
                    </li>
                    <li>
                      <Link className="btn btn-ghost normal-case text-xl" href="/about/contact">Contact</Link>
                    </li>
                    <li>
                      <Link className="btn btn-ghost normal-case text-xl" href="/githubusers">GitHub Users</Link>
                    </li>
                  </ul>
                </details>
              </li>
            </ul>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
