import Link from "next/link";
import Books from "./components/Books";

export const metadata = {
  title: "Home - My Next.js App",
  description: "Generated by create next app and my brain",
  keywords: "simple, nextjs, app, example",
};

const HomePage = () => {
  return (
    <div>
      <ul>
        <li>
          <Books/>
        </li>
      </ul>
    </div>
  );
};

export default HomePage;
