import Link from "next/link";

export const metadata = {
  title: "Home - My Next.js App",
  description: "Generated by create next app and my brain",
  keywords: "simple, nextjs, app, example",
};

const HomePage = () => {
  return (
    <div>
      <button className="btn btn-soft btn-primary">Button</button>
      <ul>
        <li>
          <Link href="/">Home</Link><br/>
          <Link href="/about">About</Link><br/>
          <Link href="/about/contact">Contact</Link>
        </li>
      </ul>
    </div>
  );
};

export default HomePage;
