export const metadata = {
  title: "About - My Next.js App",
  description: "Generated by create next app and my brain",
  keywords: "simple, nextjs, app, example",
};

const AboutPage = () => {
  return (
    <div>
      <h1>About Page</h1>
      <p>This is the about page.</p>
    </div>
  );
};

export default AboutPage;
